version: '3.8'
services:
pgadmin:
    container_name: movie-database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_NAME: ${PGSQL_DB}

    ports:
      - "5432:5432"
redis:
    container_name: redis-container
    image: redis
    ports:
      - "6379:6379"
